# Generated by Django 5.1.15 on 2026-08-17 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('job', 'Job'), ('internship', 'Internship'), ('offcampus', 'Off-campus'), ('wfh', 'Work from Home')], db_index=True, default='job', max_length=20)),
                ('description', models.TextField()),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full-time', max_length=20)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='onsite', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('salary_min', models.FloatField(default=0)),
                ('salary_max', models.FloatField(default=0)),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('stipend', 'Stipend'), ('unpaid', 'Unpaid')], default='monthly', max_length=20)),
                ('salary_currency', models.CharField(default='INR', max_length=10)),
                ('is_paid', models.BooleanField(default=True)),
                ('education', models.CharField(blank=True, default='', max_length=255)),
                ('experience', models.CharField(default='fresher', max_length=50)),
                ('application_url', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('expired', 'Expired')], db_index=True, default='published', max_length=20)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('seo_keywords', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='categories.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='companies.company')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['type', 'status', '-published_at'], name='opportuniti_type_26f7e3_idx'), models.Index(fields=['category', 'status', '-published_at'], name='opportuniti_categor_10b850_idx'), models.Index(fields=['featured', 'status', '-published_at'], name='opportuniti_feature_23e127_idx')],
            },
        ),
    ]
